# .streamlit/secrets.toml

SUPABASE_URL = "https://zldxzlbkoayhyhzxpjrq.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsZHh6bGJrb2F5aHloenhwanJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjI4MjUyNTAsImV4cCI6MjAzODQwMTI1MH0.1EiGAwelh9l2cSe11zNTuJzGu2PlpuCVmWFS-_8TC2E"